# Generated by GPT-5.2 on 2026-05-08

from django.db import migrations


def seed_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    def upsert(username, password, role, is_staff=False, is_superuser=False):
        user, created = User.objects.get_or_create(
            username=username,
            defaults={
                "role": role,
                "is_staff": is_staff,
                "is_superuser": is_superuser,
            },
        )
        if created:
            user.set_password(password)
            user.save(update_fields=["password"])
        return user

    upsert("admin", "admin123", role="admin", is_staff=True, is_superuser=True)
    upsert("advertiser1", "ad123", role="advertiser")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_users, migrations.RunPython.noop),
    ]

