# Generated by Django 5.1 on 2026-04-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignmetricrow',
            name='conversions',
        ),
        migrations.RemoveField(
            model_name='campaignmetricrow',
            name='geo',
        ),
    ]
