# Generated by Django 5.1 on 2026-05-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_remove_campaignmetricrow_conversions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='brief',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='screenshot',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, default='live', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
