# Generated by Django 5.1 on 2026-05-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_brief_campaign_end_date_campaign_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignmetricrow',
            name='age',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='campaignmetricrow',
            name='app',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='campaignmetricrow',
            name='carrier',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='campaignmetricrow',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='campaignmetricrow',
            name='creative',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='campaignmetricrow',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='campaignmetricrow',
            name='domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
